org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# android.newDsl is not needed with AGP 8.7+
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
systemProp.java.net.preferIPv4Stack=true
org.gradle.java.home=/Users/umeshpagere/.gemini/jdk17/Contents/Home
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
